name: ci
on: push
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Print node version
        run: node -v

      - name: Check production dependencies
        run: npm audit --report --omit dev

      - name: Run Cypress tests 🧪
        # https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v5
        with:
          start: 'npm start'
          wait-on: 'http://127.0.0.1:3000'
          wait-on-timeout: 30

  release:
    needs: [test]
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Install only the semantic release 📦
        run: npm install semantic-release

      - name: Semantic Release 🚀
        # https://github.com/cycjimmy/semantic-release-action
        uses: cycjimmy/semantic-release-action@v3
        with:
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
